# Generated by Django 5.1.4 on 2026-01-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_financialtransaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialcategory',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
