# Generated by Django 5.1.4 on 2026-01-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='code',
        ),
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('business', 'cpf'), name='uniq_cpf_per_business'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('business', 'code'), name='uniq_supplier_code_per_business'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('business', 'cnpj'), name='uniq_cnpj_per_business'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('business', 'code'), name='uniq_customer_code_per_business'),
        ),
    ]
